import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import HeaderUI from '@/components/common/headerUI'
import FooterUI from '@/components/common/footerUI'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt">
      <body className={inter.className}>
        <div className="flex flex-col min-h-screen">
          <HeaderUI />
          <div className='flex-grow'>{children}</div>
          <FooterUI />
        </div>
      </body>
    </html>
  )
}
